import bpy

from rna_prop_ui import rna_idprop_ui_create

from mathutils import Color


def create(obj):  # noqa
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    for i in range(10):
        arm.rigify_colors.add()

    arm.rigify_colors[0].name = "Red"
    arm.rigify_colors[0].active = Color((1.0000, 0.0000, 0.0000))
    arm.rigify_colors[0].normal = Color((0.9080, 0.0000, 0.0000))
    arm.rigify_colors[0].select = Color((0.8218, 0.0000, 0.0000))
    arm.rigify_colors[0].standard_colors_lock = True
    arm.rigify_colors[1].name = "Yellow"
    arm.rigify_colors[1].active = Color((1.0000, 1.0000, 0.0000))
    arm.rigify_colors[1].normal = Color((0.8506, 0.8506, 0.0782))
    arm.rigify_colors[1].select = Color((0.8966, 0.8966, 0.0000))
    arm.rigify_colors[1].standard_colors_lock = True
    arm.rigify_colors[2].name = "Cyan"
    arm.rigify_colors[2].active = Color((0.0000, 1.0000, 0.9449))
    arm.rigify_colors[2].normal = Color((0.0000, 0.7902, 0.7466))
    arm.rigify_colors[2].select = Color((0.1201, 0.8707, 0.8293))
    arm.rigify_colors[2].standard_colors_lock = True
    arm.rigify_colors[3].name = "Purple"
    arm.rigify_colors[3].active = Color((1.0000, 0.0000, 1.0000))
    arm.rigify_colors[3].normal = Color((0.7241, 0.0000, 0.7241))
    arm.rigify_colors[3].select = Color((0.7701, 0.0000, 0.7701))
    arm.rigify_colors[3].standard_colors_lock = True
    arm.rigify_colors[4].name = "Green"
    arm.rigify_colors[4].active = Color((0.0102, 1.0000, 0.0082))
    arm.rigify_colors[4].normal = Color((0.0084, 0.8276, 0.0068))
    arm.rigify_colors[4].select = Color((0.0081, 0.7931, 0.0065))
    arm.rigify_colors[4].standard_colors_lock = True
    arm.rigify_colors[5].name = "Orange"
    arm.rigify_colors[5].active = Color((1.0000, 0.1772, 0.0000))
    arm.rigify_colors[5].normal = Color((0.8767, 0.1711, 0.0191))
    arm.rigify_colors[5].select = Color((0.8135, 0.1588, 0.0178))
    arm.rigify_colors[5].standard_colors_lock = True
    arm.rigify_colors[6].name = "Blue"
    arm.rigify_colors[6].active = Color((0.0000, 0.3456, 1.0000))
    arm.rigify_colors[6].normal = Color((0.0000, 0.2741, 0.7931))
    arm.rigify_colors[6].select = Color((0.0783, 0.3651, 0.9080))
    arm.rigify_colors[6].standard_colors_lock = True
    arm.rigify_colors[7].name = "Dark Green"
    arm.rigify_colors[7].active = Color((0.0069, 0.3493, 0.0008))
    arm.rigify_colors[7].normal = Color((0.0046, 0.2344, 0.0005))
    arm.rigify_colors[7].select = Color((0.0047, 0.1878, 0.0006))
    arm.rigify_colors[7].standard_colors_lock = True
    arm.rigify_colors[8].name = "Pale Yellow"
    arm.rigify_colors[8].active = Color((0.9838, 1.0000, 0.1040))
    arm.rigify_colors[8].normal = Color((0.9315, 1.0000, 0.3752))
    arm.rigify_colors[8].select = Color((0.7173, 0.7701, 0.2889))
    arm.rigify_colors[8].standard_colors_lock = True
    arm.rigify_colors[9].name = "Pale Red"
    arm.rigify_colors[9].active = Color((1.0000, 0.0575, 0.0575))
    arm.rigify_colors[9].normal = Color((0.8678, 0.0898, 0.0898))
    arm.rigify_colors[9].select = Color((0.7931, 0.0820, 0.0820))
    arm.rigify_colors[9].standard_colors_lock = True

    bone_collections = {}

    for bcoll in list(arm.collections_all):
        arm.collections.remove(bcoll)

    def add_bone_collection(name, *, parent=None, ui_row=0, ui_title='', sel_set=False, color_set_id=0):
        new_bcoll = arm.collections.new(
            name, parent=bone_collections.get(parent))
        new_bcoll.rigify_ui_row = ui_row
        new_bcoll.rigify_ui_title = ui_title
        new_bcoll.rigify_sel_set = sel_set
        new_bcoll.rigify_color_set_id = color_set_id
        bone_collections[name] = new_bcoll

    def assign_bone_collections(pose_bone, *coll_names):
        assert not len(pose_bone.bone.collections)
        for name in coll_names:
            bone_collections[name].assign(pose_bone)

    def assign_bone_collection_refs(params, attr_name, *coll_names):
        ref_list = getattr(params, attr_name + '_coll_refs', None)
        if ref_list is not None:
            for name in coll_names:
                ref_list.add().set_collection(bone_collections[name])

    add_bone_collection('Face', ui_row=1, color_set_id=3)
    add_bone_collection('Face (Primary)', ui_row=1, color_set_id=3)
    add_bone_collection('Face (Secondary)', ui_row=1, color_set_id=3)
    add_bone_collection('Torso (IK)', ui_row=2, color_set_id=2)
    add_bone_collection('Torso (FK)', ui_row=2, color_set_id=5)
    add_bone_collection('Torso (Tweak)', ui_row=2, color_set_id=4)
    add_bone_collection('Arm.L (IK)', ui_row=4, color_set_id=2)
    add_bone_collection('Arm.L (FK)', ui_row=4, color_set_id=5)
    add_bone_collection('Arm.L (Tweak)', ui_row=4, color_set_id=4)
    add_bone_collection('Arm.R (IK)', ui_row=5, color_set_id=2)
    add_bone_collection('Arm.R (FK)', ui_row=5, color_set_id=5)
    add_bone_collection('Arm.R (Tweak)', ui_row=5, color_set_id=4)
    add_bone_collection('Fingers.L', ui_row=7, color_set_id=2)
    add_bone_collection('Fingers.L (Tweak)', ui_row=7, color_set_id=4)
    add_bone_collection('Fingers.R', ui_row=8, color_set_id=2)
    add_bone_collection('Fingers.R (Tweak)', ui_row=8, color_set_id=4)
    add_bone_collection('Leg.L (IK)', ui_row=10, color_set_id=2)
    add_bone_collection('Leg.L (FK)', ui_row=10, color_set_id=5)
    add_bone_collection('Leg.L (Tweak)', ui_row=10, color_set_id=4)
    add_bone_collection('Leg.R (IK)', ui_row=11, color_set_id=2)
    add_bone_collection('Leg.R (FK)', ui_row=11, color_set_id=5)
    add_bone_collection('Leg.R (Tweak)', ui_row=11, color_set_id=4)
    add_bone_collection('Root', ui_row=13, color_set_id=1)

    bones = {}

    bone = arm.edit_bones.new('Pelvis')
    bone.head = 0.0000, 0.0552, 1.0099
    bone.tail = 0.0000, 0.0172, 1.1573
    bone.roll = 0.0000
    bone.use_connect = False
    bones['Pelvis'] = bone.name
    bone = arm.edit_bones.new('Root')
    bone.head = 0.0000, 0.0000, 0.0000
    bone.tail = -0.0000, 0.5000, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bones['Root'] = bone.name
    bone = arm.edit_bones.new('Spine_01')
    bone.head = 0.0000, 0.0172, 1.1573
    bone.tail = 0.0000, 0.0004, 1.2929
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Pelvis']]
    bones['Spine_01'] = bone.name
    bone = arm.edit_bones.new('Hip.L')
    bone.head = 0.0000, 0.0552, 1.0099
    bone.tail = 0.1112, -0.0451, 1.1533
    bone.roll = -1.0756
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Pelvis']]
    bones['Hip.L'] = bone.name
    bone = arm.edit_bones.new('Hip.R')
    bone.head = -0.0000, 0.0552, 1.0099
    bone.tail = -0.1112, -0.0451, 1.1533
    bone.roll = 1.0756
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Pelvis']]
    bones['Hip.R'] = bone.name
    bone = arm.edit_bones.new('Thigh.L')
    bone.head = 0.0980, 0.0124, 1.0720
    bone.tail = 0.0980, -0.0286, 0.5372
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Pelvis']]
    bones['Thigh.L'] = bone.name
    bone = arm.edit_bones.new('Thigh.R')
    bone.head = -0.0980, 0.0124, 1.0720
    bone.tail = -0.0980, -0.0286, 0.5372
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Pelvis']]
    bones['Thigh.R'] = bone.name
    bone = arm.edit_bones.new('Spine_02')
    bone.head = 0.0000, 0.0004, 1.2929
    bone.tail = 0.0000, 0.0059, 1.4657
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Spine_01']]
    bones['Spine_02'] = bone.name
    bone = arm.edit_bones.new('Shin.L')
    bone.head = 0.0980, -0.0286, 0.5372
    bone.tail = 0.0980, 0.0162, 0.0852
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Thigh.L']]
    bones['Shin.L'] = bone.name
    bone = arm.edit_bones.new('Shin.R')
    bone.head = -0.0980, -0.0286, 0.5372
    bone.tail = -0.0980, 0.0162, 0.0852
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Thigh.R']]
    bones['Shin.R'] = bone.name
    bone = arm.edit_bones.new('Chest')
    bone.head = 0.0000, 0.0059, 1.4657
    bone.tail = 0.0000, 0.0114, 1.6582
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Spine_02']]
    bones['Chest'] = bone.name
    bone = arm.edit_bones.new('Foot.L')
    bone.head = 0.0980, 0.0162, 0.0852
    bone.tail = 0.0980, -0.0934, 0.0167
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Shin.L']]
    bones['Foot.L'] = bone.name
    bone = arm.edit_bones.new('Foot.R')
    bone.head = -0.0980, 0.0162, 0.0852
    bone.tail = -0.0980, -0.0934, 0.0167
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Shin.R']]
    bones['Foot.R'] = bone.name
    bone = arm.edit_bones.new('Neck_01')
    bone.head = 0.0000, 0.0114, 1.6582
    bone.tail = 0.0000, -0.0130, 1.7197
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Chest']]
    bones['Neck_01'] = bone.name
    bone = arm.edit_bones.new('Shoulder.L')
    bone.head = 0.0183, -0.0684, 1.6051
    bone.tail = 0.1694, 0.0205, 1.6050
    bone.roll = 0.0004
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Chest']]
    bones['Shoulder.L'] = bone.name
    bone = arm.edit_bones.new('Shoulder.R')
    bone.head = -0.0183, -0.0684, 1.6051
    bone.tail = -0.1694, 0.0205, 1.6050
    bone.roll = -0.0004
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Chest']]
    bones['Shoulder.R'] = bone.name
    bone = arm.edit_bones.new('Toe.L')
    bone.head = 0.0980, -0.0934, 0.0167
    bone.tail = 0.0980, -0.1606, 0.0167
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Foot.L']]
    bones['Toe.L'] = bone.name
    bone = arm.edit_bones.new('Heel.L')
    bone.head = 0.0600, 0.0459, 0.0000
    bone.tail = 0.1400, 0.0459, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Foot.L']]
    bones['Heel.L'] = bone.name
    bone = arm.edit_bones.new('Toe.R')
    bone.head = -0.0980, -0.0934, 0.0167
    bone.tail = -0.0980, -0.1606, 0.0167
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Foot.R']]
    bones['Toe.R'] = bone.name
    bone = arm.edit_bones.new('Heel.R')
    bone.head = -0.0600, 0.0459, 0.0000
    bone.tail = -0.1400, 0.0459, 0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Foot.R']]
    bones['Heel.R'] = bone.name
    bone = arm.edit_bones.new('Neck_02')
    bone.head = 0.0000, -0.0130, 1.7197
    bone.tail = 0.0000, -0.0247, 1.7813
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Neck_01']]
    bones['Neck_02'] = bone.name
    bone = arm.edit_bones.new('Upper_Arm.L')
    bone.head = 0.1953, 0.0267, 1.5846
    bone.tail = 0.4424, 0.0885, 1.4491
    bone.roll = 2.0724
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Shoulder.L']]
    bones['Upper_Arm.L'] = bone.name
    bone = arm.edit_bones.new('Upper_Arm.R')
    bone.head = -0.1953, 0.0267, 1.5846
    bone.tail = -0.4424, 0.0885, 1.4491
    bone.roll = -2.0724
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Shoulder.R']]
    bones['Upper_Arm.R'] = bone.name
    bone = arm.edit_bones.new('Head')
    bone.head = 0.0000, -0.0247, 1.7813
    bone.tail = 0.0000, -0.0247, 1.9796
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Neck_02']]
    bones['Head'] = bone.name
    bone = arm.edit_bones.new('Forearm.L')
    bone.head = 0.4424, 0.0885, 1.4491
    bone.tail = 0.6594, 0.0492, 1.3061
    bone.roll = 2.1535
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Upper_Arm.L']]
    bones['Forearm.L'] = bone.name
    bone = arm.edit_bones.new('Forearm.R')
    bone.head = -0.4424, 0.0885, 1.4491
    bone.tail = -0.6594, 0.0492, 1.3061
    bone.roll = -2.1535
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Upper_Arm.R']]
    bones['Forearm.R'] = bone.name
    bone = arm.edit_bones.new('Hand.L')
    bone.head = 0.6594, 0.0492, 1.3061
    bone.tail = 0.7234, 0.0412, 1.2585
    bone.roll = 2.2103
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Forearm.L']]
    bones['Hand.L'] = bone.name
    bone = arm.edit_bones.new('Hand.R')
    bone.head = -0.6594, 0.0492, 1.3061
    bone.tail = -0.7234, 0.0412, 1.2585
    bone.roll = -2.2103
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Forearm.R']]
    bones['Hand.R'] = bone.name
    bone = arm.edit_bones.new('Palm_01.L')
    bone.head = 0.6921, 0.0224, 1.2882
    bone.tail = 0.7464, 0.0051, 1.2482
    bone.roll = -2.4928
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hand.L']]
    bones['Palm_01.L'] = bone.name
    bone = arm.edit_bones.new('Palm_02.L')
    bone.head = 0.6970, 0.0389, 1.2877
    bone.tail = 0.7518, 0.0277, 1.2487
    bone.roll = -2.5274
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hand.L']]
    bones['Palm_02.L'] = bone.name
    bone = arm.edit_bones.new('Palm_03.L')
    bone.head = 0.6963, 0.0545, 1.2874
    bone.tail = 0.7540, 0.0521, 1.2482
    bone.roll = -2.5843
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hand.L']]
    bones['Palm_03.L'] = bone.name
    bone = arm.edit_bones.new('Palm_04.L')
    bone.head = 0.6929, 0.0696, 1.2871
    bone.tail = 0.7528, 0.0763, 1.2428
    bone.roll = -2.5155
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hand.L']]
    bones['Palm_04.L'] = bone.name
    bone = arm.edit_bones.new('Palm_01.R')
    bone.head = -0.6921, 0.0224, 1.2882
    bone.tail = -0.7464, 0.0051, 1.2482
    bone.roll = 2.4928
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hand.R']]
    bones['Palm_01.R'] = bone.name
    bone = arm.edit_bones.new('Palm_02.R')
    bone.head = -0.6970, 0.0389, 1.2877
    bone.tail = -0.7518, 0.0277, 1.2487
    bone.roll = 2.5274
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hand.R']]
    bones['Palm_02.R'] = bone.name
    bone = arm.edit_bones.new('Palm_03.R')
    bone.head = -0.6963, 0.0544, 1.2874
    bone.tail = -0.7540, 0.0521, 1.2482
    bone.roll = 2.5843
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hand.R']]
    bones['Palm_03.R'] = bone.name
    bone = arm.edit_bones.new('Palm_04.R')
    bone.head = -0.6929, 0.0696, 1.2871
    bone.tail = -0.7528, 0.0763, 1.2428
    bone.roll = 2.5155
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hand.R']]
    bones['Palm_04.R'] = bone.name
    bone = arm.edit_bones.new('Finger_A_01.L')
    bone.head = 0.7464, 0.0051, 1.2482
    bone.tail = 0.7718, 0.0013, 1.2112
    bone.roll = -2.0315
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_01.L']]
    bones['Finger_A_01.L'] = bone.name
    bone = arm.edit_bones.new('Thumb_01.L')
    bone.head = 0.6705, 0.0214, 1.2738
    bone.tail = 0.6857, 0.0015, 1.2404
    bone.roll = -0.1587
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_01.L']]
    bones['Thumb_01.L'] = bone.name
    bone = arm.edit_bones.new('Finger_B_01.L')
    bone.head = 0.7518, 0.0277, 1.2487
    bone.tail = 0.7762, 0.0234, 1.2058
    bone.roll = -2.0067
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_02.L']]
    bones['Finger_B_01.L'] = bone.name
    bone = arm.edit_bones.new('Finger_C_01.L')
    bone.head = 0.7540, 0.0521, 1.2482
    bone.tail = 0.7715, 0.0499, 1.2070
    bone.roll = -2.0082
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_03.L']]
    bones['Finger_C_01.L'] = bone.name
    bone = arm.edit_bones.new('Finger_D_01.L')
    bone.head = 0.7528, 0.0763, 1.2428
    bone.tail = 0.7589, 0.0765, 1.2156
    bone.roll = -1.9749
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_04.L']]
    bones['Finger_D_01.L'] = bone.name
    bone = arm.edit_bones.new('Finger_A_01.R')
    bone.head = -0.7464, 0.0051, 1.2482
    bone.tail = -0.7718, 0.0012, 1.2112
    bone.roll = 2.0315
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_01.R']]
    bones['Finger_A_01.R'] = bone.name
    bone = arm.edit_bones.new('Thumb_01.R')
    bone.head = -0.6705, 0.0214, 1.2738
    bone.tail = -0.6857, 0.0015, 1.2404
    bone.roll = 0.1587
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_01.R']]
    bones['Thumb_01.R'] = bone.name
    bone = arm.edit_bones.new('Finger_B_01.R')
    bone.head = -0.7518, 0.0277, 1.2487
    bone.tail = -0.7762, 0.0233, 1.2058
    bone.roll = 2.0067
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_02.R']]
    bones['Finger_B_01.R'] = bone.name
    bone = arm.edit_bones.new('Finger_C_01.R')
    bone.head = -0.7540, 0.0521, 1.2482
    bone.tail = -0.7715, 0.0499, 1.2070
    bone.roll = 2.0082
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_03.R']]
    bones['Finger_C_01.R'] = bone.name
    bone = arm.edit_bones.new('Finger_D_01.R')
    bone.head = -0.7528, 0.0763, 1.2428
    bone.tail = -0.7589, 0.0765, 1.2156
    bone.roll = 1.9749
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Palm_04.R']]
    bones['Finger_D_01.R'] = bone.name
    bone = arm.edit_bones.new('Finger_A_02.L')
    bone.head = 0.7718, 0.0013, 1.2112
    bone.tail = 0.7840, -0.0003, 1.1858
    bone.roll = -1.8799
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_A_01.L']]
    bones['Finger_A_02.L'] = bone.name
    bone = arm.edit_bones.new('Thumb_02.L')
    bone.head = 0.6857, 0.0015, 1.2404
    bone.tail = 0.7056, -0.0057, 1.2145
    bone.roll = -0.4798
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Thumb_01.L']]
    bones['Thumb_02.L'] = bone.name
    bone = arm.edit_bones.new('Finger_B_02.L')
    bone.head = 0.7762, 0.0234, 1.2058
    bone.tail = 0.7851, 0.0218, 1.1749
    bone.roll = -1.8283
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_B_01.L']]
    bones['Finger_B_02.L'] = bone.name
    bone = arm.edit_bones.new('Finger_C_02.L')
    bone.head = 0.7715, 0.0499, 1.2070
    bone.tail = 0.7794, 0.0494, 1.1762
    bone.roll = -1.8946
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_C_01.L']]
    bones['Finger_C_02.L'] = bone.name
    bone = arm.edit_bones.new('Finger_D_02.L')
    bone.head = 0.7589, 0.0765, 1.2156
    bone.tail = 0.7618, 0.0770, 1.1932
    bone.roll = -1.9059
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_D_01.L']]
    bones['Finger_D_02.L'] = bone.name
    bone = arm.edit_bones.new('Finger_A_02.R')
    bone.head = -0.7718, 0.0012, 1.2112
    bone.tail = -0.7840, -0.0003, 1.1858
    bone.roll = 1.8799
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_A_01.R']]
    bones['Finger_A_02.R'] = bone.name
    bone = arm.edit_bones.new('Thumb_02.R')
    bone.head = -0.6857, 0.0015, 1.2404
    bone.tail = -0.7056, -0.0057, 1.2145
    bone.roll = 0.4798
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Thumb_01.R']]
    bones['Thumb_02.R'] = bone.name
    bone = arm.edit_bones.new('Finger_B_02.R')
    bone.head = -0.7762, 0.0233, 1.2058
    bone.tail = -0.7851, 0.0218, 1.1749
    bone.roll = 1.8283
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_B_01.R']]
    bones['Finger_B_02.R'] = bone.name
    bone = arm.edit_bones.new('Finger_C_02.R')
    bone.head = -0.7715, 0.0499, 1.2070
    bone.tail = -0.7794, 0.0494, 1.1762
    bone.roll = 1.8946
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_C_01.R']]
    bones['Finger_C_02.R'] = bone.name
    bone = arm.edit_bones.new('Finger_D_02.R')
    bone.head = -0.7589, 0.0765, 1.2156
    bone.tail = -0.7618, 0.0770, 1.1932
    bone.roll = 1.9059
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_D_01.R']]
    bones['Finger_D_02.R'] = bone.name
    bone = arm.edit_bones.new('Finger_A_03.L')
    bone.head = 0.7840, -0.0003, 1.1858
    bone.tail = 0.7892, 0.0006, 1.1636
    bone.roll = -1.6760
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_A_02.L']]
    bones['Finger_A_03.L'] = bone.name
    bone = arm.edit_bones.new('Thumb_03.L')
    bone.head = 0.7056, -0.0057, 1.2145
    bone.tail = 0.7194, -0.0098, 1.1995
    bone.roll = -0.5826
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Thumb_02.L']]
    bones['Thumb_03.L'] = bone.name
    bone = arm.edit_bones.new('Finger_B_03.L')
    bone.head = 0.7851, 0.0218, 1.1749
    bone.tail = 0.7888, 0.0216, 1.1525
    bone.roll = -1.7483
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_B_02.L']]
    bones['Finger_B_03.L'] = bone.name
    bone = arm.edit_bones.new('Finger_C_03.L')
    bone.head = 0.7794, 0.0494, 1.1762
    bone.tail = 0.7781, 0.0498, 1.1577
    bone.roll = -1.6582
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_C_02.L']]
    bones['Finger_C_03.L'] = bone.name
    bone = arm.edit_bones.new('Finger_D_03.L')
    bone.head = 0.7618, 0.0770, 1.1932
    bone.tail = 0.7611, 0.0772, 1.1782
    bone.roll = -1.7639
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_D_02.L']]
    bones['Finger_D_03.L'] = bone.name
    bone = arm.edit_bones.new('Finger_A_03.R')
    bone.head = -0.7840, -0.0003, 1.1858
    bone.tail = -0.7892, 0.0006, 1.1636
    bone.roll = 1.6760
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_A_02.R']]
    bones['Finger_A_03.R'] = bone.name
    bone = arm.edit_bones.new('Thumb_03.R')
    bone.head = -0.7056, -0.0057, 1.2145
    bone.tail = -0.7194, -0.0098, 1.1995
    bone.roll = 0.5826
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Thumb_02.R']]
    bones['Thumb_03.R'] = bone.name
    bone = arm.edit_bones.new('Finger_B_03.R')
    bone.head = -0.7851, 0.0218, 1.1749
    bone.tail = -0.7888, 0.0216, 1.1525
    bone.roll = 1.7483
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_B_02.R']]
    bones['Finger_B_03.R'] = bone.name
    bone = arm.edit_bones.new('Finger_C_03.R')
    bone.head = -0.7794, 0.0494, 1.1762
    bone.tail = -0.7781, 0.0498, 1.1577
    bone.roll = 1.6582
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_C_02.R']]
    bones['Finger_C_03.R'] = bone.name
    bone = arm.edit_bones.new('Finger_D_03.R')
    bone.head = -0.7618, 0.0770, 1.1932
    bone.tail = -0.7611, 0.0772, 1.1782
    bone.roll = 1.7639
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_D_02.R']]
    bones['Finger_D_03.R'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['Pelvis']]
    pbone.rigify_type = 'WayRig.spines.basic_spine'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Torso (IK)', 'Torso (FK)')
    assign_bone_collection_refs(
        pbone.rigify_parameters, 'tweak', 'Torso (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Torso (FK)')
    try:
        pbone.rigify_parameters.torso_head_tail = 0.0
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.torso_position = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_custom_pivot = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Root']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Root')
    pbone = obj.pose.bones[bones['Spine_01']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Torso (IK)', 'Torso (FK)')
    pbone = obj.pose.bones[bones['Hip.L']]
    pbone.rigify_type = 'WayRig.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.L (IK)', 'Leg.L (FK)')
    pbone = obj.pose.bones[bones['Hip.R']]
    pbone.rigify_type = 'WayRig.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.R (IK)', 'Leg.R (FK)')
    pbone = obj.pose.bones[bones['Thigh.L']]
    pbone.rigify_type = 'WayRig.limbs.leg'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.L (FK)')
    assign_bone_collection_refs(
        pbone.rigify_parameters, 'tweak', 'Leg.L (Tweak)')
    try:
        pbone.rigify_parameters.make_bendable_foot = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_pole_name = 'Knee_Pole.L'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Thigh.R']]
    pbone.rigify_type = 'WayRig.limbs.leg'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.R (FK)')
    assign_bone_collection_refs(
        pbone.rigify_parameters, 'tweak', 'Leg.R (Tweak)')
    try:
        pbone.rigify_parameters.make_bendable_foot = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_pole_name = 'Knee_Pole.R'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Spine_02']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Torso (IK)', 'Torso (FK)')
    pbone = obj.pose.bones[bones['Shin.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    pbone = obj.pose.bones[bones['Shin.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    pbone = obj.pose.bones[bones['Chest']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Torso (IK)', 'Torso (FK)')
    pbone = obj.pose.bones[bones['Foot.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    pbone = obj.pose.bones[bones['Foot.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    pbone = obj.pose.bones[bones['Neck_01']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Torso (IK)', 'Torso (FK)')
    pbone = obj.pose.bones[bones['Shoulder.L']]
    pbone.rigify_type = 'WayRig.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Arm.L (IK)', 'Arm.L (FK)')
    pbone = obj.pose.bones[bones['Shoulder.R']]
    pbone.rigify_type = 'WayRig.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Arm.R (IK)', 'Arm.R (FK)')
    pbone = obj.pose.bones[bones['Toe.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    pbone = obj.pose.bones[bones['Heel.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    pbone = obj.pose.bones[bones['Toe.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    pbone = obj.pose.bones[bones['Heel.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    pbone = obj.pose.bones[bones['Neck_02']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Torso (IK)', 'Torso (FK)')
    pbone = obj.pose.bones[bones['Upper_Arm.L']]
    pbone.rigify_type = 'WayRig.limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.L (FK)')
    assign_bone_collection_refs(
        pbone.rigify_parameters, 'tweak', 'Arm.L (Tweak)')
    try:
        pbone.rigify_parameters.ik_pole_name = 'Elbow_Pole.L'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Upper_Arm.R']]
    pbone.rigify_type = 'WayRig.limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.R (FK)')
    assign_bone_collection_refs(
        pbone.rigify_parameters, 'tweak', 'Arm.R (Tweak)')
    try:
        pbone.rigify_parameters.ik_pole_name = 'Elbow_Pole.R'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Head']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Torso (IK)', 'Torso (FK)')
    pbone = obj.pose.bones[bones['Forearm.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    pbone = obj.pose.bones[bones['Forearm.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    pbone = obj.pose.bones[bones['Hand.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    pbone = obj.pose.bones[bones['Hand.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    pbone = obj.pose.bones[bones['Palm_01.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Palm_02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Palm_03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Palm_04.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Palm_01.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Palm_02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Palm_03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Palm_04.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_A_01.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Thumb_01.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_B_01.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_C_01.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_D_01.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_A_01.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Thumb_01.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_B_01.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_C_01.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_D_01.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_A_02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Thumb_02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_B_02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_C_02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_D_02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_A_02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Thumb_02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_B_02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_C_02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_D_02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_A_03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Thumb_03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_B_03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_C_03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_D_03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.L')
    pbone = obj.pose.bones[bones['Finger_A_03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Thumb_03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_B_03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_C_03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')
    pbone = obj.pose.bones[bones['Finger_D_03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    assign_bone_collections(pbone, 'Fingers.R')

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.collections.active_index = 0

    return bones


if __name__ == "__main__":
    create(bpy.context.active_object)
